### ISSUE TITLE
云传输助手希望针对会员可以私有化部署

### ISSUE THREAD

**Issue by Godor** [cmlanche/lightningvine-docs#26]

**Comment by cmlanche** [comment]
可以考虑，先记录下，有这样需求的用户可以继续留言

**Comment by Godor** [comment]
因为公有，对你而言需要占用太多服务器资源，后期如果传图片视频之类的。文字还好。另外还有安全审查的风险。所以不如开源让有需求的会员自己部署规避风险和成本

**Comment by cmlanche** [comment]
可以考虑做，就是不知道有多少用户需要，就怕是极少数

**Comment by Godor** [comment]
主要是&nbsp; 这样就可以支持视频&nbsp; 图片&nbsp; 文件&nbsp; &nbsp;相当于一个收藏夹&nbsp; &nbsp;单独搞一个收藏夹 app 太麻烦

&nbsp;


godor
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月19日(星期四) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cmlanche/lightningvine-docs] 云传输助手希望针对会员可以私有化部署 (Issue #26)





 
可以考虑做，就是不知道有多少用户需要，就怕是极少数
 
&mdash;

**Comment by Godor** [comment]
如果放在你的服务器上的话 你的运营成本会越来越高&nbsp; 轻量化运营 不是更自由吗。
&nbsp;


godor
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年9月19日(星期四) 下午5:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cmlanche/lightningvine-docs] 云传输助手希望针对会员可以私有化部署 (Issue #26)





 
可以考虑做，就是不知道有多少用户需要，就怕是极少数
 
&mdash;

**Comment by cmlanche** [comment]
@Godor 我准备支持对象存储私服，你们只需要配置token就可以使用，你觉得如何

**Comment by Godor** [comment]
minio，webdav支持下

**Comment by cmlanche** [comment]
minio会支持，webdav已经支持啦

**Comment by cmlanche** [comment]
@Godor 已上线 2.6.0

**Comment by moli765** [comment]
![Image](https://github.com/user-attachments/assets/244f656f-ac47-4ef7-a8ea-587696e42771)
关于webdav请问不支持排序吗？目前的排序不知道基于什么排的，难以快速定位
