### ISSUE TITLE
速度极慢，未加密的情况是1MB的速度，加密1.1MB的速度

### ISSUE THREAD

**Issue by cnolka** [cmlanche/lightningvine-docs#8]
新版本速度太慢，旧版本我记得是10MB

**Comment by cmlanche** [comment]
你的WiFi环境是否有变化呢？速度跟版本没关系，WiFi 5代 5gz可以达到30M+，而且另外新版本没有修改任何文件传输这块的逻辑的

**Comment by cnolka** [comment]
不好意思，找到原因了，关闭Clash的TUN模式之后，速度正常了，非常抱歉，并不是软件的问题，是我的问题。

> 你的WiFi环境是否有变化呢？速度跟版本没关系，WiFi 5代 5gz可以达到30M+，而且另外新版本没有修改任何文件传输这块的逻辑的
